### PR TITLE
Abbreviations for over 38000 NCBI journal titles

### LINKED ISSUE #4: Abbreviations file is outdated. Not in json format
ftp://ftp.ncbi.nih.gov/pubmed/J_Entrez.txt is the latest list. It's not formated in the CSL style described here: http://citationstylist.org/abbreviations-for-zotero/  

is there a script to convert one into the other?

### PR DESCRIPTION
**Pull request by stroobandt**
Unfortunately, the early 2019 #6 PR by @retorquere went already stale, even before it ever got merged.

However, the current PR also fixes issue #4 and largely expands the amount of abbreviated [NCBI][ncbi] journals to over 38000 by including not only the _indexed_ journals, but also those that were _referenced_ by NCBI.

[JSON][json] file extraction from [XML][xml] is done in [XSLT][xslt]; which runs orders of magnitude faster than the previous interpreted Python script.

Finally, the use and contents of a number of different journal title abbreviation files is carefully documented.

---

# NCBI Journal Title Abbreviations

The abbreviations of over 38000 journal titles referenced in the [catalogue](https://www.ncbi.nlm.nih.gov/nlmcatalog/journals) of the [National Center for Biotechnology Information][ncbi], part of the US [National Library of Medicine][nlm], are [provided in JSON format](https://github.com/stroobandt/abbreviations/blob/master/ncbi/README.md#json-output). This allows [Pandoc][pandoc] and other programs to produce references with correctly abbreviated journal titles in accordance with the [American Medical Association][ama] [_Manual of Style_][style].

Topics not only cover the entire spectrum of biomedical and life sciences, but also include many related fields.

[nlm]:     https://en.wikipedia.org/wiki/United_States_National_Library_of_Medicine
[ncbi]:    https://en.wikipedia.org/wiki/National_Center_for_Biotechnology_Information
[medline]: https://en.wikipedia.org/wiki/MEDLINE
[pmc]:     https://en.wikipedia.org/wiki/PubMed_Central

[ama]:   https://www.amamanualofstyle.com
[style]: https://guides.lib.uw.edu/hsl/ama/tips

[xml]:      https://en.wikipedia.org/wiki/XML
[xslt]:     https://en.wikipedia.org/wiki/XSLT
[xsltproc]: https://en.wikipedia.org/wiki/Libxslt
[ncbi.xsl]: ../../../blob/master/ncbi/xsl/ncbi-abbreviations.xsl

[pandoc]: https://pandoc.org/MANUAL.html

[json]:         https://en.wikipedia.org/wiki/JSON

### CODE REVIEW

**Comment by retorquere** [comment]
@rmzelle I'm OK with this PR being merged instead of mine. I could use that as a starting point for prepping for npmjs releases.

**Comment by stroobandt** [comment]
@retorquere Thank you for supporting this PR.
That is very kind of you.

**Comment by retorquere** [comment]
@rmzelle is it not desirable to have this transformation? I could really use it.

**Comment by rmzelle** [comment]
@stroobandt, @retorquere, apologies for the wait.

@adam3smith, looks fine to me.

**Comment by adam3smith** [comment]
Thank you very much!

**Comment by retorquere** [comment]
The XML source files are all empty (zero bytes).

**Comment by stroobandt** [comment]
@retorquere The XML _input_ files are empty on purpose because of their file size and the fact that, because of this, these do not go down well with `git`. Moreover, these are _not_ source code files, but rather input data files.

How to obtain a fresh copy of these XML input files, is explained in detail in the accompanying [`README.md`](https://github.com/citation-style-language/abbreviations/tree/master/ncbi#input-files).

The much smaller JSON output files are included. Most users only need these.

**Pull request merged**
